// Generated by CoffeeScript 1.6.3
(function() {
  var isIe, ua, unit, window;

  window = this;

  ua = navigator.userAgent;

  isIe = !-[1];

  unit = {
    on: function(element, type, handler) {
      if (element.addEventListener) {
        element.addEventListener(type, handler, false);
      } else {
        element.attachEvent("on" + type, handler);
      }
    },
    selectTxt: function(obj, callback) {
      unit.on(obj, 'mouseup', function(ev) {
        var endIndex, sText, staIndex, target;
        ev = ev || window.event;
        target = ev.target || ev.srcElement;
        if (/input|textarea/i.test(target.tagName) && /firefox/i.test(ua)) {
          staIndex = target.selectionStart;
          endIndex = target.selectionEnd;
          if (staIndex !== endIndex) {
            sText = target.value.substring(staIndex, endIndex);
            callback && callback(sText, target);
          }
        } else {
          if (!isIe) {
            sText = document.getSelection().toString();
          } else {
            sText = document.selection.createRange().text;
          }
          if (sText !== '') {
            callback && callback(sText, target);
          }
        }
      });
    }
  };

  window.selectTxt = unit.selectTxt;

}).call(this);
